/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.accarga;


import com.views.CheckEditPDF;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Window;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Flia Castiblanco
 */
public class CheckPDF extends javax.swing.JFrame {

    /**
     * Creates new form LoginApp
     */
    public CheckPDF() {
        initComponents();                  
        InitContent();
        InitStyles();
        
        
        /* Poner Imagen en el Label usan el Objeto que creamos antes */
        this.setLocationRelativeTo(this);        
        SetImageLabel(logo, "src/main/resources/logo.png");
        SetImageLabel(camiones, "src/main/resources/camion1.png");

    }
    
    
    
    
 /*----------------------------------------------------------------*/
    private void InitStyles(){        
        imprimirLbl.putClientProperty( "FlatLaf.style", "font: 18 $semibold.font" );   
        imprimirBtn.putClientProperty( "FlatLaf.style", "font: 13 $semibold.font" );   
        //imprimirBtn.setForeground(new Color(13,138,200));  
        imprimirBtn.setBackground(Color.WHITE);
        
        atrasBtn.setBackground(Color.WHITE);    
        //atrasBtn.setForeground(new Color(13,138,200));
        atrasBtn.putClientProperty( "FlatLaf.style", "font: 13 $semibold.font" );   
    }
    
    
 /* -------- Función para mostrar la ventana RegistroP en el mismo panel que el Login ----------*/
    private void InitContent(){
       showJPanel2(new CheckEditPDF());
    }
    
    public static void  showJPanel2(JPanel p){
        p.setSize(918,1488);
        p.setLocation(0,0);
        
        contentPDF.removeAll();
        contentPDF.add(p, BorderLayout.CENTER);
        contentPDF.revalidate();
        contentPDF.repaint(); 
    }

    
    
    public static void cerrarVentana(Component component) {
    Window window = SwingUtilities.getWindowAncestor(component);
    if (window instanceof JFrame) {
        ((JFrame) window).dispose(); // Cierra el JFrame actual
    }
}


 /*----------------------------------------------------------------*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        camiones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPDF = new javax.swing.JPanel();
        imprimirBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        imprimirLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 170, 200, 200));

        camiones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(camiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 0, 615, 1080));

        contentPDF.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPDFLayout = new javax.swing.GroupLayout(contentPDF);
        contentPDF.setLayout(contentPDFLayout);
        contentPDFLayout.setHorizontalGroup(
            contentPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        contentPDFLayout.setVerticalGroup(
            contentPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1488, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(contentPDF);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 1010));

        imprimirBtn.setForeground(new java.awt.Color(40, 157, 210));
        imprimirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        imprimirBtn.setText("IMPRIMIR");
        imprimirBtn.setBorder(null);
        imprimirBtn.setBorderPainted(false);
        imprimirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimirBtn.setIconTextGap(18);
        imprimirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBtnActionPerformed(evt);
            }
        });
        bg.add(imprimirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 180, 40));

        atrasBtn.setForeground(new java.awt.Color(40, 157, 210));
        atrasBtn.setText("◀️   Atrás");
        atrasBtn.setBorder(null);
        atrasBtn.setBorderPainted(false);
        atrasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });
        bg.add(atrasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 120, 30));

        imprimirLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imprimirLbl.setText("INSPECCIÓN VEHICULAR");
        bg.add(imprimirLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 370, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBtnActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        Printable painter = null;   // NO DEBERIA EXISTIR 
        job.setPrintable(painter); // SIN FUNCIONAMIENTO
        if(job.printDialog()){
            try {
                job.print();
                
            } catch (Exception e){
                System.out.println(e.getMessage()); 
            }                
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "La impresión se ha cancelaodo \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_imprimirBtnActionPerformed

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_atrasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>                                   
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckPDF().setVisible(true);
            }
        });
    }
    
    /* ------  Objeto para Ajustar Imagenes de los Label ----------- */
    
    private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon (image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
          }
    /*-------------------------------------------------------*/
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel camiones;
    private static javax.swing.JPanel contentPDF;
    private javax.swing.JButton imprimirBtn;
    private javax.swing.JLabel imprimirLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
