/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.accarga;


import com.views.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;


/**
 *
 * @author Flia Castiblanco
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        InitStyles();
        SetDate();
        InitContent();        
        
    }

    private void InitStyles(){
        AppName.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        AppName.setForeground(Color.white);
        msj.putClientProperty( "FlatLaf.styleClass", "h4" );
        TxtAdmin.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        TxtAdmin.setForeground(Color.white);
        TxtDay.putClientProperty( "FlatLaf.style", "font: 24 $light.font" );
        TxtDay.setForeground(Color.white);
        
    }
    
    private void SetDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        TxtDay.setText(now.format (DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
        
    }
    
    private void InitContent(){
       showJPanel(new Principal());
    }
    
    public static void  showJPanel(JPanel p){
        p.setSize(750,430);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        AppName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnPrincipal = new javax.swing.JButton();
        BtnCheck = new javax.swing.JButton();
        BtnConductores = new javax.swing.JButton();
        BtnLicencia = new javax.swing.JButton();
        BtnVehiculos = new javax.swing.JButton();
        BtnOficinas = new javax.swing.JButton();
        BtnPEntrega = new javax.swing.JButton();
        BtnHistorial = new javax.swing.JButton();
        BtnLogOut = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        TxtAdmin = new javax.swing.JLabel();
        TxtDay = new javax.swing.JLabel();
        msj = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1032, 640));

        background.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(40, 157, 210));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppName.setText("AC CARGA APP");
        menu.add(AppName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 258, 50));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, 230, 10));

        BtnPrincipal.setBackground(new java.awt.Color(13, 138, 200));
        BtnPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        BtnPrincipal.setText("Principal");
        BtnPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnPrincipal.setBorderPainted(false);
        BtnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPrincipal.setIconTextGap(14);
        BtnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrincipalActionPerformed(evt);
            }
        });
        menu.add(BtnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 270, 46));

        BtnCheck.setBackground(new java.awt.Color(13, 138, 200));
        BtnCheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCheck.setForeground(new java.awt.Color(255, 255, 255));
        BtnCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checklist.png"))); // NOI18N
        BtnCheck.setText("CHECKLIST DIGITAL");
        BtnCheck.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnCheck.setBorderPainted(false);
        BtnCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCheck.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCheck.setIconTextGap(14);
        BtnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCheckActionPerformed(evt);
            }
        });
        menu.add(BtnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 221, 270, 46));

        BtnConductores.setBackground(new java.awt.Color(13, 138, 200));
        BtnConductores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConductores.setForeground(new java.awt.Color(255, 255, 255));
        BtnConductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conductores.png"))); // NOI18N
        BtnConductores.setText("Conductores");
        BtnConductores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnConductores.setBorderPainted(false);
        BtnConductores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConductores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnConductores.setIconTextGap(14);
        BtnConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConductoresActionPerformed(evt);
            }
        });
        menu.add(BtnConductores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 267, 270, 46));

        BtnLicencia.setBackground(new java.awt.Color(13, 138, 200));
        BtnLicencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLicencia.setForeground(new java.awt.Color(255, 255, 255));
        BtnLicencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/licence.png"))); // NOI18N
        BtnLicencia.setText("Licencia de Transito");
        BtnLicencia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnLicencia.setBorderPainted(false);
        BtnLicencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLicencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLicencia.setIconTextGap(14);
        BtnLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLicenciaActionPerformed(evt);
            }
        });
        menu.add(BtnLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 313, 270, 46));

        BtnVehiculos.setBackground(new java.awt.Color(13, 138, 200));
        BtnVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        BtnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car.png"))); // NOI18N
        BtnVehiculos.setText("Vehiculos");
        BtnVehiculos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnVehiculos.setBorderPainted(false);
        BtnVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnVehiculos.setIconTextGap(14);
        BtnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVehiculosActionPerformed(evt);
            }
        });
        menu.add(BtnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 359, 270, 46));

        BtnOficinas.setBackground(new java.awt.Color(13, 138, 200));
        BtnOficinas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnOficinas.setForeground(new java.awt.Color(255, 255, 255));
        BtnOficinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina.png"))); // NOI18N
        BtnOficinas.setText("Auxiliares");
        BtnOficinas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnOficinas.setBorderPainted(false);
        BtnOficinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnOficinas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOficinas.setIconTextGap(14);
        BtnOficinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOficinasActionPerformed(evt);
            }
        });
        menu.add(BtnOficinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 405, 270, 46));

        BtnPEntrega.setBackground(new java.awt.Color(13, 138, 200));
        BtnPEntrega.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPEntrega.setForeground(new java.awt.Color(255, 255, 255));
        BtnPEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/P_entrega.png"))); // NOI18N
        BtnPEntrega.setText("Puntos de Entrega");
        BtnPEntrega.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnPEntrega.setBorderPainted(false);
        BtnPEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPEntrega.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPEntrega.setIconTextGap(14);
        BtnPEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPEntregaActionPerformed(evt);
            }
        });
        menu.add(BtnPEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 451, 270, 46));

        BtnHistorial.setBackground(new java.awt.Color(13, 138, 200));
        BtnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        BtnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/history.png"))); // NOI18N
        BtnHistorial.setText("Historial de Operaciones");
        BtnHistorial.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnHistorial.setBorderPainted(false);
        BtnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnHistorial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnHistorial.setIconTextGap(14);
        BtnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHistorialActionPerformed(evt);
            }
        });
        menu.add(BtnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 497, 270, 46));

        BtnLogOut.setBackground(new java.awt.Color(13, 138, 200));
        BtnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/history.png"))); // NOI18N
        BtnLogOut.setText("Cierra Sesión");
        BtnLogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnLogOut.setBorderPainted(false);
        BtnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLogOut.setIconTextGap(14);
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });
        menu.add(BtnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 270, 46));

        header.setBackground(new java.awt.Color(13, 127, 185));
        header.setPreferredSize(new java.awt.Dimension(744, 150));

        TxtAdmin.setText("La plataforma para gestionar tus viajes y más!");

        TxtDay.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(TxtAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        msj.setText("Nos encanta tenerte de vuelta! ❤️");

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(750, 450));
        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(msj, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(msj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrincipalActionPerformed
        // Al hacer click
        showJPanel(new Principal());
    }//GEN-LAST:event_BtnPrincipalActionPerformed

    private void BtnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCheckActionPerformed
        // Al hacer clik, mostrar la pantalla Checklist
        showJPanel(new CheckHome());
        
    }//GEN-LAST:event_BtnCheckActionPerformed

    private void BtnLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLicenciaActionPerformed
        showJPanel(new Licencias());
    }//GEN-LAST:event_BtnLicenciaActionPerformed

    private void BtnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVehiculosActionPerformed
        // TODO add your handling code here:
        showJPanel(new Vehiculos());
    }//GEN-LAST:event_BtnVehiculosActionPerformed

    private void BtnOficinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOficinasActionPerformed
                
    }//GEN-LAST:event_BtnOficinasActionPerformed

    private void BtnPEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPEntregaActionPerformed

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        //Al Hacer Click, Ir a la pantalla login:
        LoginApp newframe = new LoginApp();        
        newframe.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtnLogOutActionPerformed

    private void BtnConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConductoresActionPerformed
        // TODO add your handling code here:
        showJPanel(new conductores());
    }//GEN-LAST:event_BtnConductoresActionPerformed

    private void BtnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//        FlatMaterialLighterIJTheme.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppName;
    private javax.swing.JButton BtnCheck;
    private javax.swing.JButton BtnConductores;
    private javax.swing.JButton BtnHistorial;
    private javax.swing.JButton BtnLicencia;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnOficinas;
    private javax.swing.JButton BtnPEntrega;
    private javax.swing.JButton BtnPrincipal;
    private javax.swing.JButton BtnVehiculos;
    private javax.swing.JLabel TxtAdmin;
    private javax.swing.JLabel TxtDay;
    private javax.swing.JPanel background;
    private static javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel msj;
    // End of variables declaration//GEN-END:variables
}
