/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.views;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Flia Castiblanco
 */
public class CheckEstado extends javax.swing.JPanel {
    
    
    
    
    /**
     * Creates new form Principal
     */
    public CheckEstado() {
        initComponents();
        InitStyles();
                        
        
    }

    private void InitStyles(){
        
        Title.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        fechaTxt.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        consecutivoTxt.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        StatusVehH1.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
        
        //ViewTxt1.setForeground(Color.black);
        // ViewTxt2.putClientProperty( "FlatLaf.styleClass", "large" );
        
        
    }
    
     
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        consecutivoTxt = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        StatusVehH1 = new javax.swing.JLabel();
        StatusLlantsH2 = new javax.swing.JLabel();
        NumLlantsLbl = new javax.swing.JLabel();
        ObsLlantsLbl = new javax.swing.JLabel();
        StatusBtn1 = new javax.swing.JRadioButton();
        StatusBtn2 = new javax.swing.JRadioButton();
        StatusBtn3 = new javax.swing.JRadioButton();
        StatusBtn4 = new javax.swing.JRadioButton();
        LlantsTxt1 = new javax.swing.JTextField();
        LlantsTxt2 = new javax.swing.JTextField();
        LlantsTxt3 = new javax.swing.JTextField();
        LlantsTxt4 = new javax.swing.JTextField();
        ObsLlantsTxt1 = new javax.swing.JTextField();
        ObsLlantsTxt2 = new javax.swing.JTextField();
        ObsLlantsTxt3 = new javax.swing.JTextField();
        ObsLlantsTxt4 = new javax.swing.JTextField();
        ObsLbl = new javax.swing.JLabel();
        ObsTxt = new javax.swing.JTextField();
        StatusCarpaH2 = new javax.swing.JLabel();
        LimpiaLbl = new javax.swing.JLabel();
        LimpiBox = new javax.swing.JComboBox<>();
        LimpiaTxt = new javax.swing.JTextField();
        PerforLbl = new javax.swing.JLabel();
        PerforBox = new javax.swing.JComboBox<>();
        PerforTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        StatusCarrH2 = new javax.swing.JLabel();
        ObsCarrLbl = new javax.swing.JLabel();
        StCarrBtn1 = new javax.swing.JRadioButton();
        StCarrBtn2 = new javax.swing.JRadioButton();
        NotaCarrBtn2 = new javax.swing.JLabel();
        StCarrBtn3 = new javax.swing.JRadioButton();
        ObCarrTxt1 = new javax.swing.JTextField();
        ObCarrTxt2 = new javax.swing.JTextField();
        ObCarrTxt3 = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        Title.setText("Checklist Pre-operacional - Estado del Vehículo");

        consecutivoTxt.setText("No. 001");

        fechaTxt.setText("4/03/2024");

        StatusVehH1.setText("Estado del Vehículo");

        StatusLlantsH2.setText("Estado de Llantas");

        NumLlantsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumLlantsLbl.setText("Cúantas?");

        ObsLlantsLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ObsLlantsLbl.setText("Observaciones");

        StatusBtn1.setText("Bueno (Con Grabado)");
        StatusBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusBtn1ActionPerformed(evt);
            }
        });

        StatusBtn2.setText("Regular (Lisa)");
        StatusBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusBtn2ActionPerformed(evt);
            }
        });

        StatusBtn3.setText("Malo (Mostrando Lona)");
        StatusBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusBtn3ActionPerformed(evt);
            }
        });

        StatusBtn4.setText("Tiene Repuesto");
        StatusBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusBtn4ActionPerformed(evt);
            }
        });

        LlantsTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlantsTxt1ActionPerformed(evt);
            }
        });

        LlantsTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlantsTxt2ActionPerformed(evt);
            }
        });

        LlantsTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlantsTxt4ActionPerformed(evt);
            }
        });

        ObsLlantsTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObsLlantsTxt1ActionPerformed(evt);
            }
        });

        ObsLlantsTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObsLlantsTxt2ActionPerformed(evt);
            }
        });

        ObsLlantsTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObsLlantsTxt3ActionPerformed(evt);
            }
        });

        ObsLlantsTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObsLlantsTxt4ActionPerformed(evt);
            }
        });

        ObsLbl.setText("Observaciones");

        StatusCarpaH2.setText("Estado de Carpa");

        LimpiaLbl.setText("Limpia");

        LimpiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        LimpiBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiBoxActionPerformed(evt);
            }
        });

        LimpiaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiaTxtActionPerformed(evt);
            }
        });

        PerforLbl.setText("Perforaciones");

        PerforBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        PerforBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerforBoxActionPerformed(evt);
            }
        });

        PerforTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerforTxtActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        StatusCarrH2.setText("Estado de la Carrocería");

        ObsCarrLbl.setText("Observaciones");

        StCarrBtn1.setText("Compuertas en Buen Estado");
        StCarrBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StCarrBtn1ActionPerformed(evt);
            }
        });

        StCarrBtn2.setText("Tablas en Buen estado");
        StCarrBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StCarrBtn2ActionPerformed(evt);
            }
        });

        NotaCarrBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NotaCarrBtn2.setText("(Ninguna debe estar rota)");

        StCarrBtn3.setText("Carrocería Limpia");
        StCarrBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StCarrBtn3ActionPerformed(evt);
            }
        });

        ObCarrTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObCarrTxt1ActionPerformed(evt);
            }
        });

        ObCarrTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObCarrTxt2ActionPerformed(evt);
            }
        });

        ObCarrTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObCarrTxt3ActionPerformed(evt);
            }
        });

        nextBtn.setText("Siguiente");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(consecutivoTxt)
                        .addGap(34, 34, 34)
                        .addComponent(fechaTxt))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StatusVehH1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(StatusLlantsH2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(NumLlantsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(ObsLlantsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(StatusBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(LlantsTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(ObsLlantsTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(StatusBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(LlantsTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(ObsLlantsTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(StatusBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(LlantsTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(ObsLlantsTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(StatusBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(LlantsTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(ObsLlantsTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ObsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ObsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatusCarpaH2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(LimpiaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(LimpiBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(LimpiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(PerforLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(PerforBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(PerforTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(StatusCarrH2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StCarrBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StCarrBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NotaCarrBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StCarrBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ObsCarrLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(ObCarrTxt2)
                                            .addComponent(ObCarrTxt3)
                                            .addComponent(ObCarrTxt1)))
                                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consecutivoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(StatusVehH1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StatusLlantsH2)
                                        .addComponent(NumLlantsLbl)
                                        .addComponent(ObsLlantsLbl))
                                    .addGap(12, 12, 12)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StatusBtn1)
                                        .addComponent(LlantsTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ObsLlantsTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(7, 7, 7)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StatusBtn2)
                                        .addComponent(LlantsTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ObsLlantsTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(8, 8, 8)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StatusBtn3)
                                        .addComponent(LlantsTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ObsLlantsTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(8, 8, 8)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StatusBtn4)
                                        .addComponent(LlantsTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ObsLlantsTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(8, 8, 8)
                                    .addComponent(ObsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(ObsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addComponent(StatusCarpaH2)
                                    .addGap(14, 14, 14)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LimpiaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LimpiBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LimpiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PerforLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PerforBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PerforTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(StatusCarrH2)
                                    .addGap(12, 12, 12)
                                    .addComponent(StCarrBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(StCarrBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(NotaCarrBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(StCarrBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(ObsCarrLbl)
                                    .addGap(12, 12, 12)
                                    .addComponent(ObCarrTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(ObCarrTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(ObCarrTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void StatusBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusBtn4ActionPerformed

    private void StatusBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusBtn1ActionPerformed

    private void StatusBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusBtn2ActionPerformed

    private void StatusBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusBtn3ActionPerformed

    private void LlantsTxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlantsTxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LlantsTxt4ActionPerformed

    private void LimpiBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiBoxActionPerformed

    private void PerforBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerforBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerforBoxActionPerformed

    private void LlantsTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlantsTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LlantsTxt1ActionPerformed

    private void LimpiaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiaTxtActionPerformed

    private void LlantsTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlantsTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LlantsTxt2ActionPerformed

    private void PerforTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerforTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerforTxtActionPerformed

    private void ObsLlantsTxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObsLlantsTxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObsLlantsTxt4ActionPerformed

    private void ObsLlantsTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObsLlantsTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObsLlantsTxt1ActionPerformed

    private void ObsLlantsTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObsLlantsTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObsLlantsTxt2ActionPerformed

    private void ObsLlantsTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObsLlantsTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObsLlantsTxt3ActionPerformed

    private void ObCarrTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObCarrTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObCarrTxt1ActionPerformed

    private void StCarrBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StCarrBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StCarrBtn1ActionPerformed

    private void StCarrBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StCarrBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StCarrBtn2ActionPerformed

    private void ObCarrTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObCarrTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObCarrTxt2ActionPerformed

    private void ObCarrTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObCarrTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObCarrTxt3ActionPerformed

    private void StCarrBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StCarrBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StCarrBtn3ActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LimpiBox;
    private javax.swing.JLabel LimpiaLbl;
    private javax.swing.JTextField LimpiaTxt;
    private javax.swing.JTextField LlantsTxt1;
    private javax.swing.JTextField LlantsTxt2;
    private javax.swing.JTextField LlantsTxt3;
    private javax.swing.JTextField LlantsTxt4;
    private javax.swing.JLabel NotaCarrBtn2;
    private javax.swing.JLabel NumLlantsLbl;
    private javax.swing.JTextField ObCarrTxt1;
    private javax.swing.JTextField ObCarrTxt2;
    private javax.swing.JTextField ObCarrTxt3;
    private javax.swing.JLabel ObsCarrLbl;
    private javax.swing.JLabel ObsLbl;
    private javax.swing.JLabel ObsLlantsLbl;
    private javax.swing.JTextField ObsLlantsTxt1;
    private javax.swing.JTextField ObsLlantsTxt2;
    private javax.swing.JTextField ObsLlantsTxt3;
    private javax.swing.JTextField ObsLlantsTxt4;
    private javax.swing.JTextField ObsTxt;
    private javax.swing.JComboBox<String> PerforBox;
    private javax.swing.JLabel PerforLbl;
    private javax.swing.JTextField PerforTxt;
    private javax.swing.JRadioButton StCarrBtn1;
    private javax.swing.JRadioButton StCarrBtn2;
    private javax.swing.JRadioButton StCarrBtn3;
    private javax.swing.JRadioButton StatusBtn1;
    private javax.swing.JRadioButton StatusBtn2;
    private javax.swing.JRadioButton StatusBtn3;
    private javax.swing.JRadioButton StatusBtn4;
    private javax.swing.JLabel StatusCarpaH2;
    private javax.swing.JLabel StatusCarrH2;
    private javax.swing.JLabel StatusLlantsH2;
    private javax.swing.JLabel StatusVehH1;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel consecutivoTxt;
    private javax.swing.JLabel fechaTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
