/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.views;

import com.accarga.DAOVehiculoImpl;
import com.accarga.Dashboard;
import com.interfaces.DAOVehiculos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Flia Castiblanco
 */
public class CheckHome extends javax.swing.JPanel {
    
    
    
    
    /**
     * Creates new form Principal
     */
    public CheckHome() {
        initComponents();
        InitStyles();                        
        
    }

    private void InitStyles(){
        
        Title.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
        Title2.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
               
    }
    
     
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        historyCheck = new javax.swing.JToggleButton();
        NewCheck = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("O ver los que has Realizado");
        bg.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 344, 37));

        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("Elige si Quieres Crear un Nuevo Checklist");
        bg.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 410, 37));

        historyCheck.setBackground(new java.awt.Color(13, 138, 200));
        historyCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        historyCheck.setForeground(new java.awt.Color(255, 255, 255));
        historyCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/history.png"))); // NOI18N
        historyCheck.setText("Checklist Anteriores");
        historyCheck.setBorderPainted(false);
        historyCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyCheck.setIconTextGap(12);
        historyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyCheckActionPerformed(evt);
            }
        });
        bg.add(historyCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 260, 110));

        NewCheck.setBackground(new java.awt.Color(13, 138, 200));
        NewCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewCheck.setForeground(new java.awt.Color(255, 255, 255));
        NewCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checklist.png"))); // NOI18N
        NewCheck.setText("Nuevo Checklist");
        NewCheck.setBorderPainted(false);
        NewCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewCheck.setIconTextGap(12);
        NewCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCheckActionPerformed(evt);
            }
        });
        bg.add(NewCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 260, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void historyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyCheckActionPerformed
        // TODO add your handling code here:
        Dashboard.showJPanel(new CheckHistory());
    }//GEN-LAST:event_historyCheckActionPerformed

    private void NewCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCheckActionPerformed
        // TODO add your handling code here:
        Dashboard.showJPanel(new Checklist());
    }//GEN-LAST:event_NewCheckActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton NewCheck;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title2;
    private javax.swing.JPanel bg;
    private javax.swing.JToggleButton historyCheck;
    // End of variables declaration//GEN-END:variables
}
