/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.views;

import com.accarga.CheckPDF;
import com.accarga.DAOChecklistImpl;
import com.interfaces.DAOChecklist;
import java.awt.Color;
import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Flia Castiblanco
 */
public class Check_2 extends javax.swing.JPanel {
    
    
    
    
    /**
     * Creates new form Principal
     */
    public Check_2() {
        initComponents();
        InitStyles();
        SetDate();
        id_autoincrement();
                        
        
    }

    private void InitStyles(){
        
        Title.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        fechaTxt.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        consecutivoTxt.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        //GeneralTitle.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
        DocsTitle1.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
        DocsTitle2.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
        DocsTitle3.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
        //ViewTxt1.setForeground(Color.black);
        // ViewTxt2.putClientProperty( "FlatLaf.styleClass", "large" );                        
    }
    
    private void SetDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        fechaTxt.setText(now.format (DateTimeFormatter.ofPattern("dd '/' MM '/' yyyy", spanishLocale)));
        
    }
    
    private void id_autoincrement(){
        
         com.models.Checklist check = new com.models.Checklist();
         
         try {            
            DAOChecklist dao = new DAOChecklistImpl();                      
            //dao.autoincrement(consecutivoTxt);
            dao.UltimoId(check);            
            String idCheckFk = String.valueOf(check.getId_checklist_fk());
            consecutivoTxt.setText("Codigo: GL-F-00" + idCheckFk);
            
            

            //String idCheckFk = String.valueOf(check.getId_checklist_fk());
            
        } catch(Exception e) {                    
            //Si hubo un error en la conexión con BD, o con la Incersión de Datos, entonces:
            System.out.println(e.getMessage()); 
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un Error al importar el consecutivo \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }                  
     }
     
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DocsTitle1 = new javax.swing.JLabel();
        SoatLbl = new javax.swing.JLabel();
        SoatBox = new javax.swing.JComboBox<>();
        RevLbl1 = new javax.swing.JLabel();
        RevLbl2 = new javax.swing.JLabel();
        RevBox = new javax.swing.JComboBox<>();
        EPSLbl = new javax.swing.JLabel();
        EPSBox = new javax.swing.JComboBox<>();
        GlGasoliLbl = new javax.swing.JLabel();
        GlGasoliTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        DocsTitle2 = new javax.swing.JLabel();
        Carpa_LimLbl = new javax.swing.JLabel();
        CarpaLimBox = new javax.swing.JComboBox<>();
        CarpaPerfBox = new javax.swing.JComboBox<>();
        DocsTitle3 = new javax.swing.JLabel();
        CarrCompLbl = new javax.swing.JLabel();
        CarrCompBox = new javax.swing.JComboBox<>();
        CarrTablesLbl = new javax.swing.JLabel();
        CarrTablesBox = new javax.swing.JComboBox<>();
        CarrLimpiaLbl = new javax.swing.JLabel();
        CarrLimpiaBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarrObsTXT = new javax.swing.JTextArea();
        nextBtn = new javax.swing.JButton();
        consecutivoTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setText("Checklist Pre-operacional");
        bg.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 17, 144, 37));

        fechaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaTxt.setText("4/03/2024");
        bg.add(fechaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 17, 80, 37));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 60, 686, 10));

        DocsTitle1.setText("Verificación de Documentos");
        bg.add(DocsTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 80, 263, 37));

        SoatLbl.setText("SOAT VIGENTE");
        bg.add(SoatLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 139, 117, 40));

        SoatBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        SoatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoatBoxActionPerformed(evt);
            }
        });
        bg.add(SoatBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 129, 40));

        RevLbl1.setText("REVISIÓN TÉCNICO");
        bg.add(RevLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 117, -1));

        RevLbl2.setText("MECANICA VIGENTE");
        bg.add(RevLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 117, -1));

        RevBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        RevBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevBoxActionPerformed(evt);
            }
        });
        bg.add(RevBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 129, 40));

        EPSLbl.setText("ARL Y EPS VIGENTE");
        bg.add(EPSLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 117, 40));

        EPSBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        EPSBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSBoxActionPerformed(evt);
            }
        });
        bg.add(EPSBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 129, 40));

        GlGasoliLbl.setText("Galones de Gasolina");
        bg.add(GlGasoliLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 35));
        bg.add(GlGasoliTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 130, 35));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 83, 10, 330));

        DocsTitle2.setText("Estado de Carpa");
        bg.add(DocsTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 80, 263, 37));

        Carpa_LimLbl.setText("Limpia");
        bg.add(Carpa_LimLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 50, 30));

        CarpaLimBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        CarpaLimBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarpaLimBoxActionPerformed(evt);
            }
        });
        bg.add(CarpaLimBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 80, 30));

        CarpaPerfBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        CarpaPerfBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarpaPerfBoxActionPerformed(evt);
            }
        });
        bg.add(CarpaPerfBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 80, 30));

        DocsTitle3.setText("Estado de Carrocería");
        bg.add(DocsTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 263, 30));

        CarrCompLbl.setText("Compuertas en Buen Estado");
        bg.add(CarrCompLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 160, 25));

        CarrCompBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        CarrCompBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrCompBoxActionPerformed(evt);
            }
        });
        bg.add(CarrCompBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 120, 25));

        CarrTablesLbl.setText("Tablas en Buen Estado (0 Rotas)");
        bg.add(CarrTablesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 170, 25));

        CarrTablesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        CarrTablesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrTablesBoxActionPerformed(evt);
            }
        });
        bg.add(CarrTablesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 120, 25));

        CarrLimpiaLbl.setText("Carrocería Limpia");
        bg.add(CarrLimpiaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 170, 25));

        CarrLimpiaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        CarrLimpiaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrLimpiaBoxActionPerformed(evt);
            }
        });
        bg.add(CarrLimpiaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 120, 25));

        CarrObsTXT.setColumns(20);
        CarrObsTXT.setRows(5);
        jScrollPane1.setViewportView(CarrObsTXT);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 310, 50));

        nextBtn.setBackground(new java.awt.Color(13, 138, 200));
        nextBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Siguiente");
        nextBtn.setBorder(null);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        bg.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 383, 110, 30));

        consecutivoTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bg.add(consecutivoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        
        String soat = (String) SoatBox.getSelectedItem();
        String TMecanica = (String) RevBox.getSelectedItem();
        String EPS = (String) EPSBox.getSelectedItem();
        String gasolina = GlGasoliTxt.getText();
        String carpaLim =(String) CarpaLimBox.getSelectedItem();
        String carpaPerf =(String) CarpaPerfBox.getSelectedItem();
        String carrComp = (String) CarrCompBox.getSelectedItem();
        String carrTables = (String) CarrTablesBox.getSelectedItem();
        String carrLimpia =(String) CarrLimpiaBox.getSelectedItem();
        String carrObs = CarrObsTXT.getText();
        
                                
        //Validaciones para los campos de texto
        // Si uno de lso campos requerido estpa vacío(isEmpty), ocurrirá lo siguiente:
        if(soat.isEmpty() || TMecanica.isEmpty() || EPS.isEmpty() || gasolina.isEmpty() || carpaLim.isEmpty() || carpaPerf.isEmpty() || carrComp.isEmpty() || carrTables.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            SoatBox.requestFocus();       //Establece el cursor en el campo de la cedula
            return;                         //Con esto, vamos a parar la ejecución del Boton, y paramos la incersión a la BD hasta que se llenen los campos requeridos
        }                                
        com.models.Checklist check = new com.models.Checklist();                
        
        //check.setId_checklist_fk();
        
        check.setGl_combustible(Integer.parseInt(gasolina));
        check.setSoat_vigente(soat);
        check.setTMecanica_vigente(TMecanica);
        check.setArl_eps_vigente(EPS);
        check.setCarpa_limpia(carpaLim);
        check.setCarpa_perf(carpaPerf);
        check.setCarr_compu_Bestado(carrComp);
        check.setCarr_tablas_Bestado(carrTables);
        check.setCarr_limpia(carrLimpia);
        check.setCarr_obser(carrObs);
        
        
        try {
            
            DAOChecklist dao = new DAOChecklistImpl();            
            dao.UltimoId(check);            
            String idCheckFk = String.valueOf(check.getId_checklist_fk());
            check.setId_checklist_fk(Integer.parseInt(idCheckFk));
            
            dao.registroCheckFolio(check);
            javax.swing.JOptionPane.showMessageDialog(this, "Check 1 bien \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);            
            
            //Dashboard.showJPanel(new CheckEstado());
            CheckPDF newframe = new CheckPDF();
            newframe.setVisible(true);                    
            
            
        } catch(Exception e) {                    
            //Si hubo un error en la conexión con BD, o con la Incersión de Datos, entonces:
            System.out.println(e.getMessage()); 
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un Error al Registrar al Usuario \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_nextBtnActionPerformed

    private void CarpaPerfBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarpaPerfBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarpaPerfBoxActionPerformed

    private void CarrCompBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrCompBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarrCompBoxActionPerformed

    private void EPSBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSBoxActionPerformed

    private void RevBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RevBoxActionPerformed

    private void SoatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoatBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoatBoxActionPerformed

    private void CarpaLimBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarpaLimBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarpaLimBoxActionPerformed

    private void CarrTablesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrTablesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarrTablesBoxActionPerformed

    private void CarrLimpiaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrLimpiaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarrLimpiaBoxActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CarpaLimBox;
    private javax.swing.JComboBox<String> CarpaPerfBox;
    private javax.swing.JLabel Carpa_LimLbl;
    private javax.swing.JComboBox<String> CarrCompBox;
    private javax.swing.JLabel CarrCompLbl;
    private javax.swing.JComboBox<String> CarrLimpiaBox;
    private javax.swing.JLabel CarrLimpiaLbl;
    private javax.swing.JTextArea CarrObsTXT;
    private javax.swing.JComboBox<String> CarrTablesBox;
    private javax.swing.JLabel CarrTablesLbl;
    private javax.swing.JLabel DocsTitle1;
    private javax.swing.JLabel DocsTitle2;
    private javax.swing.JLabel DocsTitle3;
    private javax.swing.JComboBox<String> EPSBox;
    private javax.swing.JLabel EPSLbl;
    private javax.swing.JLabel GlGasoliLbl;
    private javax.swing.JTextField GlGasoliTxt;
    private javax.swing.JComboBox<String> RevBox;
    private javax.swing.JLabel RevLbl1;
    private javax.swing.JLabel RevLbl2;
    private javax.swing.JComboBox<String> SoatBox;
    private javax.swing.JLabel SoatLbl;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel consecutivoTxt;
    private javax.swing.JLabel fechaTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
