/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.views;

import com.accarga.DAOConductorImpl;
import com.accarga.LoginApp;
import static com.accarga.LoginApp.cerrarVentana;
import static com.accarga.LoginApp.showJPanel2;
import com.interfaces.DAOConductor;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Flia Castiblanco
 */
public class LoginP extends javax.swing.JPanel {

    /**
     * Creates new form registroP
     */
    public LoginP() {
        initComponents();
        InitStyles();
    }

    private void InitStyles(){
        TitleLogin.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        TitleLogin.setForeground(Color.black);
        userLbl.putClientProperty( "FlatLaf.style", "font: 12 $semibold.font" );
        PassLbl.putClientProperty( "FlatLaf.style", "font: 12 $semibold.font" );   
        
        RegisterBtn.setBackground(Color.WHITE);
        
        UserTxt.putClientProperty("JTextField.placeholderText", "Ingrese su Cedula");
        PassTxt.putClientProperty("JTextField.placeholderText", "Ingrese su Contraseña");
                
    }    
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        favicon = new javax.swing.JLabel();
        TitleLogin = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        UserTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        PassLbl = new javax.swing.JLabel();
        PassTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        RegisterBtn = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favicon.png"))); // NOI18N

        TitleLogin.setText("INICIAR SESION");

        userLbl.setText("USUARIO");

        UserTxt.setBorder(null);
        UserTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTxtActionPerformed(evt);
            }
        });

        PassLbl.setText("CONTRASEÑA");

        PassTxt.setBorder(null);
        PassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("🔒 Olvidaste la Contraseña?");

        LoginBtn.setBackground(new java.awt.Color(13, 138, 200));
        LoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("ENTRAR");
        LoginBtn.setBorder(null);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        RegisterBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(13, 138, 200));
        RegisterBtn.setText("REGISTRARME");
        RegisterBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 138, 200), 3));
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(favicon)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(TitleLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(150, 150, 150))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(userLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(150, 150, 150))
                    .addComponent(UserTxt)
                    .addComponent(jSeparator1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(PassLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(150, 150, 150))
                    .addComponent(PassTxt)
                    .addComponent(jSeparator2)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGap(230, 230, 230))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(RegisterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90)))
                .addGap(112, 112, 112))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(favicon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(TitleLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(userLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(UserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PassLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(PassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(54, 54, 54)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UserTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTxtActionPerformed

    private void PassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTxtActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String userC = UserTxt.getText();
        String passC = PassTxt.getText();
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

        try {
            DAOConductor dao = new DAOConductorImpl();
            dao.login((String) userC, (String)passC, frame);
            //javax.swing.JOptionPane.showMessageDialog(null, "Bienvenido Querido Conductor  \n", "BIENVENIDA", javax.swing.JOptionPane.INFORMATION_MESSAGE;
            //cerrarVentana(this); // 'this' se refiere al JPanel actual
                         

        } catch(Exception e) {
            //Si hubo un error en la conexión con BD, o con la Incersión de Datos, entonces:
            System.out.println(e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un Error al Iniciar Sesión \n", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        showJPanel2(new registroP());

    }//GEN-LAST:event_RegisterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JTextField PassTxt;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel TitleLogin;
    private javax.swing.JTextField UserTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel favicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel userLbl;
    // End of variables declaration//GEN-END:variables
}
