/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.views;

import com.accarga.DAOConductorImpl;
import com.accarga.LoginApp;
import static com.accarga.LoginApp.cerrarVentana;
import static com.accarga.LoginApp.showJPanel2;
import com.interfaces.DAOConductor;
import java.awt.Color;
import java.math.BigInteger;
import java.security.MessageDigest;

/**
 *
 * @author Flia Castiblanco
 */
public class registroP extends javax.swing.JPanel {

    /**
     * Creates new form registroP
     */
    public registroP() {
        initComponents();
        InitStyles();
    }

    private void InitStyles(){
        TitleLbl1.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        TitleLbl2.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        TitleLbl22.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        TitleLbl22.setForeground(new Color(13,138,200));  
        createLbl.putClientProperty( "FlatLaf.style", "font: 15 $semibold.font" );   
        
        cedulaTxt.putClientProperty("JTextField.placeholderText", "No.Cedula");
        DateNacimTxt.putClientProperty("JTextField.placeholderText", "Fecha Nacimiento");
        NameTxt.putClientProperty("JTextField.placeholderText", "Nombres");
        apellido1Txt.putClientProperty("JTextField.placeholderText", "Primer Apellido");
        apellido2Txt.putClientProperty("JTextField.placeholderText", "Segundo Apellido");
        TelTxt.putClientProperty("JTextField.placeholderText", "No. Celular");
        cityTxt.putClientProperty("JTextField.placeholderText", "Ciudad");
        DireccionTxt.putClientProperty("JTextField.placeholderText", "Direccion");
        EPSTxt.putClientProperty("JTextField.placeholderText", "EPS");
        ARLTxt.putClientProperty("JTextField.placeholderText", "ARL");
        SoatTxt.putClientProperty("JTextField.placeholderText", "No. SOAT");
        emailTxt.putClientProperty("JTextField.placeholderText", "Correo Electronico");
        passTxt.putClientProperty("JTextField.placeholderText", "Contraseña");
        
        LoginPBtn.setBackground(Color.WHITE);
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        TitleLbl1 = new javax.swing.JLabel();
        TitleLbl2 = new javax.swing.JLabel();
        TitleLbl22 = new javax.swing.JLabel();
        fastLbl = new javax.swing.JLabel();
        TipoIDBox = new javax.swing.JComboBox<>();
        cedulaTxt = new javax.swing.JTextField();
        DateNacimTxt = new javax.swing.JTextField();
        NameTxt = new javax.swing.JTextField();
        apellido1Txt = new javax.swing.JTextField();
        apellido2Txt = new javax.swing.JTextField();
        IndTelBox = new javax.swing.JComboBox<>();
        TelTxt = new javax.swing.JTextField();
        TipoUserBox = new javax.swing.JComboBox<>();
        cityTxt = new javax.swing.JTextField();
        DireccionTxt = new javax.swing.JTextField();
        EPSTxt = new javax.swing.JTextField();
        ARLTxt = new javax.swing.JTextField();
        SoatTxt = new javax.swing.JTextField();
        createLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        LoginPBtn = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        TitleLbl1.setText("Hola!");

        TitleLbl2.setText("Bienvenido a");

        TitleLbl22.setText("AC CARGA APP");

        fastLbl.setText("Registrarse es muy fácil y rápido!");

        TipoIDBox.setForeground(new java.awt.Color(153, 153, 153));
        TipoIDBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo ID", "C.C", "C.E", "T.I" }));
        TipoIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoIDBoxActionPerformed(evt);
            }
        });

        cedulaTxt.setForeground(new java.awt.Color(153, 153, 153));
        cedulaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTxtActionPerformed(evt);
            }
        });

        DateNacimTxt.setForeground(new java.awt.Color(153, 153, 153));
        DateNacimTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateNacimTxtActionPerformed(evt);
            }
        });

        NameTxt.setForeground(new java.awt.Color(153, 153, 153));
        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });

        apellido1Txt.setForeground(new java.awt.Color(153, 153, 153));
        apellido1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1TxtActionPerformed(evt);
            }
        });

        apellido2Txt.setForeground(new java.awt.Color(153, 153, 153));
        apellido2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido2TxtActionPerformed(evt);
            }
        });

        IndTelBox.setForeground(new java.awt.Color(153, 153, 153));
        IndTelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+57", "+59", "+1" }));

        TelTxt.setForeground(new java.awt.Color(153, 153, 153));
        TelTxt.setToolTipText("No. Celular");

        TipoUserBox.setForeground(new java.awt.Color(153, 153, 153));
        TipoUserBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qué eres?", "Conductor", "Administrador", "Auxiliar" }));
        TipoUserBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoUserBoxActionPerformed(evt);
            }
        });

        cityTxt.setForeground(new java.awt.Color(153, 153, 153));
        cityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtActionPerformed(evt);
            }
        });

        DireccionTxt.setForeground(new java.awt.Color(153, 153, 153));
        DireccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionTxtActionPerformed(evt);
            }
        });

        EPSTxt.setForeground(new java.awt.Color(153, 153, 153));
        EPSTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSTxtActionPerformed(evt);
            }
        });

        ARLTxt.setForeground(new java.awt.Color(153, 153, 153));
        ARLTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARLTxtActionPerformed(evt);
            }
        });

        SoatTxt.setForeground(new java.awt.Color(153, 153, 153));
        SoatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoatTxtActionPerformed(evt);
            }
        });

        createLbl.setText("Crea tu Cuenta para Iniciar Sesión");

        emailTxt.setForeground(new java.awt.Color(153, 153, 153));

        passTxt.setForeground(new java.awt.Color(153, 153, 153));
        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(13, 138, 200));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Inicia Sesión");
        loginBtn.setBorder(null);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        LoginPBtn.setForeground(new java.awt.Color(153, 153, 153));
        LoginPBtn.setText("️◀");
        LoginPBtn.setBorder(null);
        LoginPBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoginPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(passTxt))
                        .addGap(62, 62, 62)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(createLbl)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(EPSTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ARLTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fastLbl)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(TitleLbl2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TitleLbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TitleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                            .addComponent(apellido1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellido2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(TipoIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(DateNacimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(IndTelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TipoUserBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(SoatTxt)
                        .addComponent(NameTxt)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(TitleLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLbl2)
                    .addComponent(TitleLbl22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fastLbl)
                .addGap(27, 27, 27)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateNacimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndTelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoUserBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EPSTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ARLTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SoatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createLbl)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(LoginPBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TipoIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoIDBoxActionPerformed

    private void cedulaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaTxtActionPerformed

    private void DateNacimTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateNacimTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateNacimTxtActionPerformed

    private void apellido1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido1TxtActionPerformed

    private void apellido2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido2TxtActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String cedula = cedulaTxt.getText();
        String nombre = NameTxt.getText();
        String apellido1 = apellido1Txt.getText();
        String apellido2 = apellido2Txt.getText();
        String Tel = TelTxt.getText();
        String ciudad = cityTxt.getText();
        String direccion = DireccionTxt.getText();
        String EPS = EPSTxt.getText();
        String ARL = ARLTxt.getText();
        String soat = SoatTxt.getText();
        String Email = emailTxt.getText();
        String Pass = passTxt.getText();
        String tipoUser = (String) TipoUserBox.getSelectedItem();

          //Se coloco el codigo de encriptar
        String sha1 = "";
        
            		// With the java libraries
	try {
                        MessageDigest digest = MessageDigest.getInstance("SHA-1");
	        digest.reset();
	        digest.update(Pass.getBytes("utf8"));
	        sha1 = String.format("%040x", new BigInteger(1, digest.digest()));
	} catch (Exception e){
	    e.printStackTrace();
	}
      
        
        //Validaciones para los campos de texto
        // Si uno de lso campos requerido estpa vacío(isEmpty), ocurrirá lo siguiente:
        if(cedula.isEmpty() || nombre.isEmpty() || apellido1.isEmpty() || Tel.isEmpty() || ciudad.isEmpty() || direccion.isEmpty() || EPS.isEmpty() || ARL.isEmpty() || soat.isEmpty() || Email.isEmpty() || Pass.isEmpty() || tipoUser.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            cedulaTxt.requestFocus();       //Establece el cursor en el campo de la cedula
            return;                         //Con esto, vamos a parar la ejecución del Boton, y paramos la incersión a la BD hasta que se llenen los campos requeridos
        }
            
                    
        com.models.Conductores conductor = new com.models.Conductores();        
        conductor.setId_conductor(Integer.parseInt(cedula));
        conductor.setNombre_cond(nombre);
        conductor.setApellido_1(apellido1);
        conductor.setApellido_2(apellido2);
        conductor.setTelefono(Tel);
        conductor.setCiudad(ciudad);
        conductor.setDireccion(direccion);
        conductor.setEPS(EPS);
        conductor.setARL(ARL);
        conductor.setSoat(soat);
        conductor.setEmail(Email);
        conductor.setContraseña(Pass);
        conductor.setTipo_user(tipoUser);
        
        try {
            
            DAOConductor dao = new DAOConductorImpl();
            dao.registrar(conductor);
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario Ingresado con Exito \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cedulaTxt.setText("");
            NameTxt.setText("");
            apellido1Txt.setText("");
            apellido2Txt.setText("");
            TelTxt.setText("");
            cityTxt.setText("");
            DireccionTxt.setText("");
            EPSTxt.setText("");
            ARLTxt.setText("");
            SoatTxt.setText("");
            emailTxt.setText("");
            passTxt.setText("");                                                
            
            showJPanel2(new LoginP());
            
            
        } catch(Exception e) {                    
            //Si hubo un error en la conexión con BD, o con la Incersión de Datos, entonces:
            System.out.println(e.getMessage()); 
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un Error al Registrar al Usuario \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            
        }
        
                
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtActionPerformed

    private void DireccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionTxtActionPerformed

    private void EPSTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSTxtActionPerformed

    private void ARLTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARLTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ARLTxtActionPerformed

    private void SoatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoatTxtActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void TipoUserBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoUserBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoUserBoxActionPerformed

    private void LoginPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPBtnActionPerformed
       
        showJPanel2(new LoginP());        

        
    }//GEN-LAST:event_LoginPBtnActionPerformed

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ARLTxt;
    private javax.swing.JTextField DateNacimTxt;
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.JTextField EPSTxt;
    private javax.swing.JComboBox<String> IndTelBox;
    private javax.swing.JButton LoginPBtn;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField SoatTxt;
    private javax.swing.JTextField TelTxt;
    private javax.swing.JComboBox<String> TipoIDBox;
    private javax.swing.JComboBox<String> TipoUserBox;
    private javax.swing.JLabel TitleLbl1;
    private javax.swing.JLabel TitleLbl2;
    private javax.swing.JLabel TitleLbl22;
    private javax.swing.JTextField apellido1Txt;
    private javax.swing.JTextField apellido2Txt;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel createLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel fastLbl;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField passTxt;
    // End of variables declaration//GEN-END:variables
}
