/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.views;

import com.accarga.DAOLicenciaImpl;
import com.interfaces.DAOLicencia;


/**
 *
 * @author Flia Castiblanco
 */
public class UpLicencias extends javax.swing.JPanel {
    
    boolean isEdition = false;  // Incializamos el Boolean "isEdition" en False(Lo ponemos como predeterminado)
    com.models.Licencias licenciaEdition;
    
    
    /**
     * Creates new form Principal
     */
    public UpLicencias() {
        initComponents();
        InitStyles();          
    }
    
                                                          
    public UpLicencias(com.models.Licencias licencia){           
        initComponents();
        isEdition = true;                                // Si el parametro de la función InitStyles es true para "isEdition", Entonces se podrán rellenar los campos de Txt con la info a editar.
        licenciaEdition = licencia;
        InitStyles();
    }
    

    private void InitStyles(){
        
        // Titulos en Semibold para Lbl
        Title.putClientProperty( "FlatLaf.style", "font: 20 $semibold.font" );
        GeneralTitle.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        IDConductorLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        dateExpLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        dateVenLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );                
        EstadoLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );        
        RestLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        CategoriaLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );

        
        // Placeholders para Txt
        IDLicTxt.putClientProperty("JTextField.placeholderText", "Numero Licencia");
        IDConductorTxt.putClientProperty("JTextField.placeholderText", "Cedula del Propietario");        
        dateExpTxt.putClientProperty("JTextField.placeholderText", "Expedición");
        dateVenTxt.putClientProperty("JTextField.placeholderText", "Vencimiento");
        EstadoTxt.putClientProperty("JTextField.placeholderText", "Estado");
        CategoriaTxt.putClientProperty("JTextField.placeholderText", "Categoria");
        RestTxt.putClientProperty("JTextField.placeholderText", "Enlista las Restricciones");
        
        
        
        
        
        if(isEdition){
            Title.setText("Editar Licencia");
            saveBtn.setText("Guardar");
            
            if(licenciaEdition != null){      //Cuando los Txt estén vacíos, se rellenan con los datos del "conductor" seleccionado (todos los datos de cada Conductor se almacenan en la "clase" "conductorEdition" para poder editarlos)
                
                IDLicTxt.setText(String.valueOf(licenciaEdition.getId_licencia()));
                IDConductorTxt.setText(String.valueOf(licenciaEdition.getCedula_cond()));
                dateExpTxt.setText(String.valueOf(licenciaEdition.getFecha_Expedicion()));
                dateVenTxt.setText(String.valueOf(licenciaEdition.getFecha_Vencimiento()));
                EstadoTxt.setText(String.valueOf(licenciaEdition.getEstado_Lic()));
                CategoriaTxt.setText(String.valueOf(licenciaEdition.getCategoriaLic()));
                RestTxt.setText(String.valueOf(licenciaEdition.getRestriccion_Lic()));
                                
                
            }
        
        }  
        

    }
    
     
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        GeneralTitle = new javax.swing.JLabel();
        IDLicTxt = new javax.swing.JTextField();
        IDConductorLbl = new javax.swing.JLabel();
        IDConductorTxt = new javax.swing.JTextField();
        dateExpLbl = new javax.swing.JLabel();
        dateExpTxt = new javax.swing.JTextField();
        dateVenLbl = new javax.swing.JLabel();
        dateVenTxt = new javax.swing.JTextField();
        EstadoLbl = new javax.swing.JLabel();
        EstadoTxt = new javax.swing.JTextField();
        CategoriaTxt = new javax.swing.JTextField();
        CategoriaLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        RestLbl = new javax.swing.JLabel();
        RestTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        Title.setText("Registrar Nueva Licencia de Conducción");

        GeneralTitle.setText("Numero de Licencia");

        IDLicTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLicTxtActionPerformed(evt);
            }
        });

        IDConductorLbl.setText("Cedula del Conductor");

        IDConductorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDConductorTxtActionPerformed(evt);
            }
        });

        dateExpLbl.setText("Fecha Expedición");

        dateExpTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateExpTxtActionPerformed(evt);
            }
        });

        dateVenLbl.setText("Fecha Vencimiento");

        dateVenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateVenTxtActionPerformed(evt);
            }
        });

        EstadoLbl.setText("Estado de Licencia");

        EstadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoTxtActionPerformed(evt);
            }
        });

        CategoriaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaTxtActionPerformed(evt);
            }
        });

        CategoriaLbl.setText("Categoría de Licencia");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        RestLbl.setText("Restricciones");

        saveBtn.setBackground(new java.awt.Color(13, 138, 200));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Registrar");
        saveBtn.setBorder(null);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(GeneralTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dateExpLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(dateExpTxt)
                                                .addComponent(EstadoTxt))
                                            .addGap(36, 36, 36)
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dateVenLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(CategoriaTxt)
                                                .addComponent(dateVenTxt)))
                                        .addComponent(IDConductorTxt)
                                        .addComponent(IDLicTxt))
                                    .addGap(45, 45, 45)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(IDConductorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(EstadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(CategoriaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(11, 11, 11)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(RestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(RestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(GeneralTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(IDLicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(IDConductorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(IDConductorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateExpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(dateVenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(10, 10, 10)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateExpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateVenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EstadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CategoriaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EstadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CategoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // Boton de Guardar
        String Licencia = IDLicTxt.getText();
        String cedula = IDConductorTxt.getText();
        String dateExp = dateExpTxt.getText();
        String dateVen = dateVenTxt.getText();
        String estado = EstadoTxt.getText();
        String categoria = CategoriaTxt.getText();
        String restriccion = RestTxt.getText();
        
        
        
        //Validaciones para los campos de texto
        // Si uno de lso campos requerido estpa vacío(isEmpty), ocurrirá lo siguiente:
        if(Licencia.isEmpty() || cedula.isEmpty() || dateExp.isEmpty() || dateVen.isEmpty() || estado.isEmpty() || categoria.isEmpty() || restriccion.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            IDLicTxt.requestFocus();       
            return;                        
        }
            

        com.models.Licencias licencia = isEdition ? licenciaEdition : new com.models.Licencias();        //IF es una Edición, ENTONCES Asignale a la variable "conductor" lo que traigas en la "conductorEdition"(Es una Variable Global). SI NO se trata de una Edición de tipo conductor, CREA un NEW objeto de tipo "Conductores"
                                                                                                              // Y lo que traigas del objeto "conductor", rellenala con la info que se haya tecleado en los campos de abajo
        licencia.setId_licencia(Integer.parseInt(Licencia));
        licencia.setCedula_cond(Integer.parseInt(cedula));
        licencia.setFecha_Vencimiento(dateVen);
        licencia.setFecha_Expedicion(dateExp);
        licencia.setEstado_Lic(estado);
        licencia.setCategoriaLic(categoria);
        licencia.setRestriccion_Lic(restriccion);
        
        
        try {
            
            DAOLicencia dao = new DAOLicenciaImpl();
            
            if (!isEdition){                //IF no es una edición, registralo. ELSE modificalo
                dao.registrar(licencia);
            } else {
                dao.modificar(licencia);
            }
            
            
            String successMsg = isEdition ? "Modificada" : "Registrada";
            javax.swing.JOptionPane.showMessageDialog(this, "Licencia de Conducción " + successMsg + " con Exito \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            if(!isEdition){
                IDLicTxt.setText("");
                IDConductorTxt.setText("");
                dateExpTxt.setText("");
                dateVenTxt.setText("");
                EstadoTxt.setText("");
                CategoriaTxt.setText("");
                RestTxt.setText("");
                
                
            }
            
        } catch(Exception e) {                    
            //Si hubo un error en la conexión con BD, o con la Incersión de Datos, entonces:
            System.out.println(e.getMessage()); 
            String errorMsg = isEdition ? "Modificar" : "Registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un Error al " + errorMsg + " la Licencia de Conducción\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void dateVenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateVenTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateVenTxtActionPerformed

    private void dateExpTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateExpTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateExpTxtActionPerformed

    private void EstadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoTxtActionPerformed

    private void CategoriaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaTxtActionPerformed

    private void IDLicTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLicTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDLicTxtActionPerformed

    private void IDConductorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDConductorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDConductorTxtActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoriaLbl;
    private javax.swing.JTextField CategoriaTxt;
    private javax.swing.JLabel EstadoLbl;
    private javax.swing.JTextField EstadoTxt;
    private javax.swing.JLabel GeneralTitle;
    private javax.swing.JLabel IDConductorLbl;
    private javax.swing.JTextField IDConductorTxt;
    private javax.swing.JTextField IDLicTxt;
    private javax.swing.JLabel RestLbl;
    private javax.swing.JTextField RestTxt;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel dateExpLbl;
    private javax.swing.JTextField dateExpTxt;
    private javax.swing.JLabel dateVenLbl;
    private javax.swing.JTextField dateVenTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
