/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.views;

import com.accarga.DAOVehiculoImpl;
import com.interfaces.DAOVehiculos;

/**
 *
 * @author Flia Castiblanco
 */
public class UpVehiculos extends javax.swing.JPanel {
    
    boolean isEdition = false;  // Incializamos el Boolean "isEdition" en False(Lo ponemos como predeterminado)
    com.models.Vehiculos vehiculoEdition;
    
    
    /**
     * Creates new form Principal
     */
    public UpVehiculos() {
        initComponents();
        InitStyles();          
    }
    
                                                          
    public UpVehiculos(com.models.Vehiculos vehiculo){           
        initComponents();
        isEdition = true;                                // Si el parametro de la función InitStyles es true para "isEdition", Entonces se podrán rellenar los campos de Txt con la info a editar.
        vehiculoEdition = vehiculo;
        InitStyles();
    }
    

    private void InitStyles(){
        
        // Titulos en Semibold para Lbl
        Title.putClientProperty( "FlatLaf.style", "font: 20 $semibold.font" );
        GeneralTitle.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        IDConductorLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        tipoVehLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        tipoServLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        CapMaxLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        EstadoVehLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        KmLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        añoLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        dateMantLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        marcaLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );
        modeloLbl.putClientProperty( "FlatLaf.style", "font: $semibold.font" );

        
        // Placeholders para Txt
        IDVehTxt.putClientProperty("JTextField.placeholderText", "Placa del Vehiculo");
        IDConductorTxt.putClientProperty("JTextField.placeholderText", "Cedula del Propietario");        
        tipoVehTxt.putClientProperty("JTextField.placeholderText", "Tipo Vehiculo");
        tipoServTxt.putClientProperty("JTextField.placeholderText", "Servicio Vehiculo");
        añoTxt.putClientProperty("JTextField.placeholderText", "Año Modelo");
        modeloTxt.putClientProperty("JTextField.placeholderText", "Nombre Modelo");
        marcaTxt.putClientProperty("JTextField.placeholderText", "Nombre Marca");
        CapMaxTxt.putClientProperty("JTextField.placeholderText", "Cap. Max en TON");
        KmTxt.putClientProperty("JTextField.placeholderText", "Km Recorridos");
        EstadoVehTxt.putClientProperty("JTextField.placeholderText", "Estado del Vehiculo");
        dateMantTxt.putClientProperty("JTextField.placeholderText", "Ultimo Mantenimiento");
        
        
        
        
        if(isEdition){
            Title.setText("Editar Vehiculo");
            saveBtn.setText("Guardar");
            
            if(vehiculoEdition != null){      //Cuando los Txt estén vacíos, se rellenan con los datos del "conductor" seleccionado (todos los datos de cada Conductor se almacenan en la "clase" "conductorEdition" para poder editarlos)
                
                IDVehTxt.setText(String.valueOf(vehiculoEdition.getId_vehiculo()));
                IDConductorTxt.setText(String.valueOf(vehiculoEdition.getId_conductor()));
                tipoVehTxt.setText(String.valueOf(vehiculoEdition.getTipo_veh()));
                tipoServTxt.setText(String.valueOf(vehiculoEdition.getTipo_servicio()));
                añoTxt.setText(String.valueOf(vehiculoEdition.getAño()));
                modeloTxt.setText(String.valueOf(vehiculoEdition.getMarca()));
                marcaTxt.setText(String.valueOf(vehiculoEdition.getModelo()));
                CapMaxTxt.setText(String.valueOf(vehiculoEdition.getCapacidad_max_carga()));
                KmTxt.setText(String.valueOf(vehiculoEdition.getKm_recorrido()));
                EstadoVehTxt.setText(String.valueOf(vehiculoEdition.getEstado_veh()));
                dateMantTxt.setText(String.valueOf(vehiculoEdition.getFecha_ultimo_manten()));
                                
                
            }
        
        }  
        

    }
    
     
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        GeneralTitle = new javax.swing.JLabel();
        IDVehTxt = new javax.swing.JTextField();
        IDConductorLbl = new javax.swing.JLabel();
        IDConductorTxt = new javax.swing.JTextField();
        tipoVehLbl = new javax.swing.JLabel();
        tipoVehTxt = new javax.swing.JTextField();
        tipoServLbl = new javax.swing.JLabel();
        tipoServTxt = new javax.swing.JTextField();
        añoLbl = new javax.swing.JLabel();
        añoTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        modeloLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        marcaLbl = new javax.swing.JLabel();
        marcaTxt = new javax.swing.JTextField();
        CapMaxLbl = new javax.swing.JLabel();
        CapMaxTxt = new javax.swing.JTextField();
        KmLbl = new javax.swing.JLabel();
        KmTxt = new javax.swing.JTextField();
        EstadoVehLbl = new javax.swing.JLabel();
        EstadoVehTxt = new javax.swing.JTextField();
        dateMantLbl = new javax.swing.JLabel();
        dateMantTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        Title.setText("Registrar un Nuevo Vehiculo");

        GeneralTitle.setText("Placa del Vehiculo");

        IDVehTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDVehTxtActionPerformed(evt);
            }
        });

        IDConductorLbl.setText("Cedula del Conductor");

        IDConductorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDConductorTxtActionPerformed(evt);
            }
        });

        tipoVehLbl.setText("Tipo de Vehiculo");

        tipoVehTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVehTxtActionPerformed(evt);
            }
        });

        tipoServLbl.setText("Tipo de Servicio");

        tipoServTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoServTxtActionPerformed(evt);
            }
        });

        añoLbl.setText("Año");

        añoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoTxtActionPerformed(evt);
            }
        });

        modeloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTxtActionPerformed(evt);
            }
        });

        modeloLbl.setText("Modelo");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        marcaLbl.setText("Marca");

        CapMaxLbl.setText("Capacidad Maxima (TON)");

        CapMaxTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapMaxTxtActionPerformed(evt);
            }
        });

        KmLbl.setText("Km Recorridos");

        KmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KmTxtActionPerformed(evt);
            }
        });

        EstadoVehLbl.setText("Estado del Vehiculo");

        dateMantLbl.setText("Fecha del Ultimo Mantenimiento");

        saveBtn.setBackground(new java.awt.Color(13, 138, 200));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Registrar");
        saveBtn.setBorder(null);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(añoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(modeloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(GeneralTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tipoVehLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(tipoVehTxt)
                                                .addComponent(añoTxt))
                                            .addGap(36, 36, 36)
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tipoServLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(modeloTxt)
                                                .addComponent(tipoServTxt)))
                                        .addComponent(IDConductorTxt)
                                        .addComponent(IDVehTxt))
                                    .addGap(45, 45, 45)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(IDConductorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(marcaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(CapMaxLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CapMaxTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(31, 31, 31)
                                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(KmLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(KmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(marcaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dateMantTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EstadoVehTxt)
                                            .addComponent(dateMantLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(EstadoVehLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(41, 41, 41))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(GeneralTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(IDVehTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(IDConductorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(IDConductorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoVehLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tipoServLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoVehTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoServTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(añoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(añoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(marcaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CapMaxLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(KmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CapMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(EstadoVehLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(EstadoVehTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateMantLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(dateMantTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // Boton de Guardar
        String Placa = IDVehTxt.getText();
        String cedula = IDConductorTxt.getText();
        String tipo_veh = tipoVehTxt.getText();
        String servicio = tipoServTxt.getText();
        String año = añoTxt.getText();
        String modelo = modeloTxt.getText();
        String marca = marcaTxt.getText();
        String CapMax = CapMaxTxt.getText();
        String KmRec = KmTxt.getText();
        String estado = EstadoVehTxt.getText();
        String fecha = dateMantTxt.getText();
        
        
        
        //Validaciones para los campos de texto
        // Si uno de lso campos requerido estpa vacío(isEmpty), ocurrirá lo siguiente:
        if(Placa.isEmpty() || cedula.isEmpty() || tipo_veh.isEmpty() || servicio.isEmpty() || año.isEmpty() || modelo.isEmpty() || marca.isEmpty() || CapMax.isEmpty() || KmRec.isEmpty() || estado.isEmpty() || fecha.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            IDVehTxt.requestFocus();       
            return;                        
        }
            

        com.models.Vehiculos vehiculo = isEdition ? vehiculoEdition : new com.models.Vehiculos();        //IF es una Edición, ENTONCES Asignale a la variable "conductor" lo que traigas en la "conductorEdition"(Es una Variable Global). SI NO se trata de una Edición de tipo conductor, CREA un NEW objeto de tipo "Conductores"
                                                                                                              // Y lo que traigas del objeto "conductor", rellenala con la info que se haya tecleado en los campos de abajo
        vehiculo.setId_vehiculo(Placa);
        vehiculo.setId_conductor(Integer.parseInt(cedula));
        vehiculo.setTipo_veh(tipo_veh);
        vehiculo.setTipo_servicio(servicio);
        vehiculo.setAño(año);
        vehiculo.setModelo(modelo);
        vehiculo.setMarca(marca);
        vehiculo.setCapacidad_max_carga(Integer.parseInt(CapMax));
        vehiculo.setKm_recorrido(Float.parseFloat(KmRec));
        vehiculo.setEstado_veh(estado);
        vehiculo.setFecha_ultimo_manten(fecha);        
        
        try {
            
            DAOVehiculos dao = new DAOVehiculoImpl();
            
            if (!isEdition){                //IF no es una edición, registralo. ELSE modificalo
                dao.registrar(vehiculo);
            } else {
                dao.modificar(vehiculo);
            }
            
            
            String successMsg = isEdition ? "Modificado" : "Registrado";
            javax.swing.JOptionPane.showMessageDialog(this, "Vehiculo " + successMsg + " con Exito \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            if(!isEdition){
                IDVehTxt.setText("");
                IDConductorTxt.setText("");
                tipoVehTxt.setText("");
                tipoServTxt.setText("");
                añoTxt.setText("");
                modeloTxt.setText("");
                marcaTxt.setText("");
                CapMaxTxt.setText("");
                KmTxt.setText("");
                EstadoVehTxt.setText("");
                dateMantTxt.setText("");
                
            }
            
        } catch(Exception e) {                    
            //Si hubo un error en la conexión con BD, o con la Incersión de Datos, entonces:
            System.out.println(e.getMessage()); 
            String errorMsg = isEdition ? "Modificar" : "Registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un Error al " + errorMsg + " al Vehiculo \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void tipoServTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoServTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoServTxtActionPerformed

    private void tipoVehTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVehTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoVehTxtActionPerformed

    private void añoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoTxtActionPerformed

    private void modeloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtActionPerformed

    private void CapMaxTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapMaxTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapMaxTxtActionPerformed

    private void KmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KmTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KmTxtActionPerformed

    private void IDVehTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDVehTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDVehTxtActionPerformed

    private void IDConductorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDConductorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDConductorTxtActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CapMaxLbl;
    private javax.swing.JTextField CapMaxTxt;
    private javax.swing.JLabel EstadoVehLbl;
    private javax.swing.JTextField EstadoVehTxt;
    private javax.swing.JLabel GeneralTitle;
    private javax.swing.JLabel IDConductorLbl;
    private javax.swing.JTextField IDConductorTxt;
    private javax.swing.JTextField IDVehTxt;
    private javax.swing.JLabel KmLbl;
    private javax.swing.JTextField KmTxt;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel añoLbl;
    private javax.swing.JTextField añoTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel dateMantLbl;
    private javax.swing.JTextField dateMantTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel marcaLbl;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JLabel modeloLbl;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel tipoServLbl;
    private javax.swing.JTextField tipoServTxt;
    private javax.swing.JLabel tipoVehLbl;
    private javax.swing.JTextField tipoVehTxt;
    // End of variables declaration//GEN-END:variables
}
